config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  as :user do
    get "signin" => 'devise/sessions#new'
    delete "signout" => 'devise/sessions#destroy'
    get "signup" => 'devise/registrations#new'
  end

  root 'pages#home'
  # get '/' => 'pages#home' this is the same as the above line
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact-us'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>One Month Rails Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">Finance Calculators</a>
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contact", contact_path, class: "nav-link" %></li>
          <% if user_signed_in? %>
            <li class="nav-item pull-md-right"><%= link_to "Log out", signout_path, method: :delete, class: "nav-link btn btn-primary" %></li>
          <% else %>
            <li class="nav-item pull-md-right"><%= link_to "Sign in", signin_path, class: "nav-link" %></li>
            <li class="nav-item pull-md-right"><%= link_to "Sign up", signup_path, class: "nav-link btn btn-primary" %></li>
          <% end %>
          
          
        </ul>
      </div>
    </nav>

    <!-- Flash Messages -->
    <% flash.each do |name, message| %>
      <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
    <% end %>

    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>Stephen Charette</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container">
        <div class="row">
            <h1>About</h1>
            <p>My name is Stephen Charette and I am majoring in Computer Science at George Mason University. I am an intern with Solution Street LLC in Herndon, VA.
            I created this website so I can build calculators for certain investment vehicles as I was calculating this on a regular basis to see how much I will have
            at retirement given certain contribution targets. There are other ones online but I wanted to create my own because I wanted more features than other popular ones.</p>
        </div>
    </div>
</div>

app/views/pages/contact-us.html.erb
<div class="jumbotron">
    <div class="container">
        <div class="row">
            <h1>Contact Information</h1>
            <p>Creator email: scharette@solutionstreet.com</p>
            <a href="https://www.linkedin.com/in/stephen-charette-bb8226141/">Linkedin Profile</a>
        </div>
    </div>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>
    <div class="jumbotron jumbotron-home">
        <div class="container">
            <h1>Welcome Back!</h1>
            <%= link_to "Manage account »", "#", class: "btn btn-primary btn-lg" %> 
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h2>IRA Balance Calculator</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><%= link_to "View calculator", "#", class: "btn btn-secondary" %></p>
            </div>
            <div class="col-md-4">
                <h2>401k Balance Calculator</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><%= link_to "View calculator", "#", class: "btn btn-secondary" %></p>
            </div>
            <div class="col-md-4">
                <h2>Brokerage Balance Calculator</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><%= link_to "View calculator", "#", class: "btn btn-secondary" %></p>
            </div>
        </div>
    </div>
<% else %>
    <div class="jumbotron jumbotron-home">
        <div class="container">
            <h1>Welcome Back!</h1>
            <p>Thank you for visiting my website! By creating an account, you can use my calculators for free and we can keep track of the information in your calculators
            so you can come back anytime and have that information saved!</p>
            <%= link_to "Create an account »", signup_path, class: "btn btn-primary btn-lg" %> 
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h2>IRA Balance Calculator</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><%= link_to "Sign up to view calculator", signup_path, class: "btn btn-secondary" %></p>
            </div>
            <div class="col-md-4">
                <h2>401k Balance Calculator</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><%= link_to "Sign up to view calculator", signup_path, class: "btn btn-secondary" %></p>
            </div>
            <div class="col-md-4">
                <h2>Brokerage Balance Calculator</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><%= link_to "Sign up to view calculator", signup_path, class: "btn btn-secondary" %></p>
            </div>
        </div>
    </div>
<% end %>